export const errorName = Object.freeze({
  USER_EXISTS: "USER_EXISTS",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  EMAIL_UNCONFIRMED: "EMAIL_UNCONFIRMED",
  LOGIN_ACCOUNT_ERROR: "LOGIN_ACCOUNT_ERROR",
  HACK: "HACK",
  GOOGLE_LOGIN_ACCOUNT_ERROR: "GOOGLE_LOGIN_ACCOUNT_ERROR",
  AUTH_ERROR: "AUTH_ERROR",
  USER_NULL: "USER_NULL",
  NAME_LENGTH_ERROR: "NAME_LENGTH_ERROR",
  NAME_SPACE_ERROR: "NAME_SPACE_ERROR",
  WRONG_EMAIL: "WRONG_EMAIL",
  EMAILS_MISMATCH: "EMAILS_MISMATCH",
  WRONG_PASSWORD: "WRONG_PASSWORD"
});
